[package]
name = "nlook"
version = "0.4.0-alpha"
authors = ["zengi <nzengi>", "<n>"]
exclude = ["./tests/compose"]
edition = "2018"

[package.metadata.configure_me]
spec = "config_spec.toml"

[features]
prod_public_path = []

[dependencies]
bitcoin = { version = "0.29.2", features = ["serde"] }
payjoin = { version = "0.7.0", features = ["sender", "receiver" ] }
url = "2.2.2"
hyper = "0.14.9"
tonic_lnd = "0.5.0"
reqwest = { version = "0.11.13",  default-features = false, features = ["rustls-tls", "json", "socks"] }
tokio = { version = "1.7.1", features = ["rt-multi-thread"] }
rand = "0.8.4"
base64 = "0.13.0"
serde = "1.0.126"
serde_json = "1.0.87"
serde_qs = "0.10.1"
serde_derive = "1.0.126"
ln-types = { version = "0.1.3", features = ["serde", "parse_arg"] }
configure_me = "0.4.0"
qrcode-generator = "4.1.6"
log = "0.4.17"
env_logger = "0.9.3"

[build-dependencies]
configure_me_codegen = "0.4.3"

[dev-dependencies]
bitcoincore-rpc = "0.15.0"
rcgen =  "0.10.0"
tempfile = "3"
tonic = "0.6.2"

# in dev mode optimize crates that are perf-critical (usually just crypto crates)
[profile.dev.package]
secp256k1 = { opt-level = 2 }
secp256k1-sys = { opt-level = 2 }
rand_core = { opt-level = 2 }
byteorder = { opt-level = 2 }
